Traceback (most recent call last):
  File "/home/panxopanza/programs/miniconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/panxopanza/programs/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/panxopanza/programs/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/panxopanza/programs/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/panxopanza/programs/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/panxopanza/programs/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/panxopanza/programs/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/panxopanza/programs/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print('inv(P) = ', inv(P))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mLinAlgError[0m                               Traceback (most recent call last)
[0;32m/tmp/ipykernel_958/453559162.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mprint[0m[0;34m([0m[0;34m'inv(P) = '[0m[0;34m,[0m [0minv[0m[0;34m([0m[0mP[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/programs/miniconda3/lib/python3.9/site-packages/numpy/core/overrides.py[0m in [0;36minv[0;34m(*args, **kwargs)[0m

[0;32m~/programs/miniconda3/lib/python3.9/site-packages/numpy/linalg/linalg.py[0m in [0;36minv[0;34m(a)[0m
[1;32m    550[0m     [0msignature[0m [0;34m=[0m [0;34m'D->D'[0m [0;32mif[0m [0misComplexType[0m[0;34m([0m[0mt[0m[0;34m)[0m [0;32melse[0m [0;34m'd->d'[0m[0;34m[0m[0;34m[0m[0m
[1;32m    551[0m     [0mextobj[0m [0;34m=[0m [0mget_linalg_error_extobj[0m[0;34m([0m[0m_raise_linalgerror_singular[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 552[0;31m     [0mainv[0m [0;34m=[0m [0m_umath_linalg[0m[0;34m.[0m[0minv[0m[0;34m([0m[0ma[0m[0;34m,[0m [0msignature[0m[0;34m=[0m[0msignature[0m[0;34m,[0m [0mextobj[0m[0;34m=[0m[0mextobj[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    553[0m     [0;32mreturn[0m [0mwrap[0m[0;34m([0m[0mainv[0m[0;34m.[0m[0mastype[0m[0;34m([0m[0mresult_t[0m[0;34m,[0m [0mcopy[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    554[0m [0;34m[0m[0m

[0;32m~/programs/miniconda3/lib/python3.9/site-packages/numpy/linalg/linalg.py[0m in [0;36m_raise_linalgerror_singular[0;34m(err, flag)[0m
[1;32m     87[0m [0;34m[0m[0m
[1;32m     88[0m [0;32mdef[0m [0m_raise_linalgerror_singular[0m[0;34m([0m[0merr[0m[0;34m,[0m [0mflag[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 89[0;31m     [0;32mraise[0m [0mLinAlgError[0m[0;34m([0m[0;34m"Singular matrix"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     90[0m [0;34m[0m[0m
[1;32m     91[0m [0;32mdef[0m [0m_raise_linalgerror_nonposdef[0m[0;34m([0m[0merr[0m[0;34m,[0m [0mflag[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mLinAlgError[0m: Singular matrix
LinAlgError: Singular matrix

